Ant deploy use second i2c line i144
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #199
Opened 2024-09-27 04:11 UTC by Makiv1

implements #144 

For testing, each command was run on both buses and I verified that the correct led was lit on the electrical model.

2024-09-27 18:59 UTC, DeflateAwning commented
I saw the "don't review yet" tag. What was remaining on this one? I thought it was tested and pretty close to finished?

2024-09-27 21:00 UTC, Makiv1 commented
Hey Parker, everything was tested and works but I don't know if I'm happy with the quality of code I wrote. Let me look it over today before you start reviewing so you don't waste your time :)

2024-09-28 00:25 UTC, Makiv1 commented
Should be good for a review now!

2024-09-30 04:48 UTC, DeflateAwning requested changes
Looks awesome! Just a few easy small tweaks

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Inc/antenna_deploy_drivers/ant_commands.h
> +uint8_t ANT_CMD_reset(enum Ant_i2c_bus_mcu i2c_bus_mcu);
Please rename the enum to be `ANT_i2c_bus_mcu` (capital "ANT")

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Inc/antenna_deploy_drivers/ant_commands.h
>  struct Antenna_deployment_status {
Please rename struct to be `ANT_antenna_deployment_status`

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Src/antenna_deploy_drivers/ant_commands.c
> +                LOG_SEVERITY_WARNING,
Let's call it an "error" if it results in an early return from a function.

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Src/antenna_deploy_drivers/ant_internal_drivers.c
>  const uint8_t timeout = 50;
What units is this? Perhaps also include a comment with info about what the timeout is for (HAL_transmit, HAL_receive? Both?)

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Src/antenna_deploy_drivers/ant_internal_drivers.c
> +            DEBUG_uart_print_str("invalid i2c bus passed");
Please remove the uart print if using LOG_message.

2024-09-30 04:48 UTC, DeflateAwning commented on firmware/Core/Src/telecommands/antenna_telecommand_defs.c
> +    const int status = ANT_CMD_reset(i2c_bus_mcu);
Avoid `int` type

2024-10-02 05:35 UTC, DeflateAwning approved these changes
Thanks!

2024-10-03 04:13 UTC, merged