Automated Python Unit Testing Framework
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #206
Opened 2024-10-04 01:53 UTC by kev9268

Added unit tests for hello world, echo args and for delay ms.
Includes a function that reads and compares expected response line and input line

2024-10-04 04:48 UTC, DeflateAwning commented
This looks really neat so far! Very well done! :) 

I quite like how simple and clean the fixture part is! I'm excited to keep expanding on this! Will give it a bit more review later on.

2024-10-16 19:11 UTC, NuclearTea commented
@DeflateAwning Need some clarification on what else to add in order to complete #5 , this PR.

2024-10-19 22:05 UTC, NuclearTea requested changes

2024-10-19 22:05 UTC, NuclearTea commented on firmware/.env
Might be a good idea to prefix all of these variables with something like: "PY_TEST_...".

It could be possible that we need to use other environment variables that represent similar things, this way, you have the name distinguish them

2024-10-24 00:26 UTC, NuclearTea approved these changes
Nice!

2024-10-24 01:38 UTC, merged