EPS: Only show first 17 EPS channels in JSON renders
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #208
Opened 2024-10-04 04:36 UTC by DeflateAwning

2024-10-04 20:02 UTC, Makiv1 requested changes
Very nice! Just a few things to clarify.

2024-10-04 20:42 UTC, DeflateAwning commented on firmware/Core/Src/eps_drivers/eps_types_to_json.c
> +    for (uint8_t ch = 0; ch <= EPS_MAX_ACTIVE_CHANNEL_NUMBER; ch++) {
I did yeah! Super weird, but there are 17 out of 32 channels on our EPS (instead of the 16 that you'd expect). Thanks for checking though :)

2024-10-04 20:42 UTC, Makiv1 commented on firmware/Core/Src/eps_drivers/eps_types_to_json.c
> +        if (ch < (16 - 1)) {
or maybe `EPS_MAX_ACTIVE_CHANNEL_COUNT` is the right constant to use. Up to you.

2024-10-04 20:44 UTC, DeflateAwning commented on firmware/Core/Src/eps_drivers/eps_types_to_json.c
> +        if (ch < (16 - 1)) {
Wow, great catch!!

Correct to: `if (ch < (EPS_MAX_ACTIVE_CHANNEL_NUMBER))`

2024-10-04 20:53 UTC, Makiv1 submitted a review, later dismissed
Looks great.

2024-10-06 19:02 UTC, DeflateAwning commented
Status update @NuclearTea - Per the label, this PR is awaiting testing.

2024-10-16 02:50 UTC, DeflateAwning commented
Functions modified to be tested with telecommands:

```
EPS_struct_system_status_TO_json
EPS_struct_pdu_housekeeping_data_eng_TO_json
EPS_struct_pdu_overcurrent_fault_state_TO_json
EPS_struct_piu_housekeeping_data_eng_TO_json
```

2024-10-23 04:31 UTC, DeflateAwning commented
Tested and all works.

2024-10-23 04:31 UTC, merged