Telecommand: LFS delete file (#227)
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #233
Opened 2024-11-09 23:25 UTC by KaleF07

Resolves #227:

**Summary**
- Included telecommand that uses `LFS_delete_file` helper function to delete a file from LFS
- Accepts 1 argument: The name of the file to be deleted

2024-11-11 00:23 UTC, NuclearTea reviewed
This all looks good. This just needs to be tested.

2024-11-15 03:03 UTC, vaibhavkpr commented
> This all looks good. This just needs to be tested.

I was able to quickly test this using my NAND memory module. Looks good!
✅ Able to successfully delete a file if it exists.
✅ Reports appropriate error when trying to delete a file that doesn't exist.

Here are some things to consider that I found during testing:
⚠️ I'm unable to reach the "Error parsing file name arg" scenario when I send an empty string "" as an input. Also to note as a result "" is accepted as a parameter when creating a file. Able to reach case: 3 (filename too long for parsing) successfully.
⚠️ Able to send input both with and without "", are both ways acceptable? May be worth including in the arg doc so it is more clear.

2024-11-20 01:17 UTC, KaleF07 commented
> > This all looks good. This just needs to be tested.
> 
> I was able to quickly test this using my NAND memory module. Looks good! ✅ Able to successfully delete a file if it exists. ✅ Reports appropriate error when trying to delete a file that doesn't exist.
> 
> Here are some things to consider that I found during testing (while not directly linked to the issue itself but worth getting investigated if possible): ⚠️ I'm unable to reach the "Error parsing file name arg" scenario when I send an empty string "" as an input. Also to note as a result "" is accepted as a parameter when creating a file. Able to reach case: 3 (filename too long for parsing) successfully. ⚠️ Able to send input both with and without "", are both ways acceptable? May be worth including in the arg doc so it is more clear.

Thank you for testing! I'll take a look into the issues and get them fixed right away! Passing a filename argument of "" should not be acceptable, there should be an error case for an empty argument.

2024-11-29 02:01 UTC, KaleF07 commented
While looking through the code, I found that the "Error parsing file name arg" condition was trivial since passing no arguments to this telecommand prompts a telecommand parsing error. However, I will keep the statement in the code just to be safe.

I added a note in the doc string indicating to not add quotations around the argument when parsing `fs_delete_file` to reduce any confusion.

2024-11-29 02:05 UTC, KaleF07 commented
another good thing to mention is that it might be nice to wait until Saksham's `LFS telecommand list files [issue #7] ` is merged into main to merge this branch.

2025-02-08 07:24 UTC, DeflateAwning commented
PR #216 (list files in a directory) was just published. When you get a chance, would you mind rebasing and testing this? Then we can merge it!

2025-02-08 07:25 UTC, DeflateAwning requested changes
Just that one change; looks good otherwise!

2025-02-08 07:25 UTC, DeflateAwning commented on firmware/Core/Src/telecommands/lfs_telecommand_defs.c
> +    char arg_file_name[64] = {0};
Please change `64` to `LFS_MAX_PATH_LENGTH` const (now in main).

2025-02-12 02:12 UTC, KaleF07 commented
All changes should be implemented, ready for a approval then we can merge!

2025-02-12 02:19 UTC, DeflateAwning approved these changes
Thanks!

2025-02-12 02:21 UTC, merged