Alex on/122 gps track the pps pulse per second pulses into a counter variable since the last sync
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #239
Opened 2024-11-24 04:26 UTC by 2BlackCats

It should check to see if PIN A6(GPS_PPS_PIN) changes using a external interrupt to increase a counter. Please double check my logic. Thx

2024-12-02 00:26 UTC, NuclearTea requested changes
Code Needs to be rebased before it can be reviewed

2024-12-04 02:07 UTC, DeflateAwning requested changes
Looks good overall! Just a few fixes though.

2024-12-04 02:07 UTC, DeflateAwning commented on .vscode/settings.json
> +  "[markdown]": {
Please revert this file.

Use `git checkout main -- .vscode/settings.json`

2024-12-04 02:07 UTC, DeflateAwning commented on firmware/Core/Inc/gps/gps_pps_interrupt.h
> +extern uint8_t gps_pps_enabled;
Please prefix variables with `GPS_` (see `docs/` -> Namespace Guide for more details).

Please rename to `GPS_pps_interrupt_enabled`

2024-12-04 02:07 UTC, DeflateAwning commented on firmware/Core/Inc/gps/gps_pps_interrupt.h
> +void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin);
Are you sure you need to put this here?

2024-12-04 02:07 UTC, DeflateAwning commented on firmware/Core/Src/telecommands/gps_telecommand_defs.c
> +        }
Please fix indentation. Use 4 spaces.

2024-12-04 02:07 UTC, DeflateAwning commented on firmware/Core/Src/telecommands/telecommand_definitions.c
> +    //*******************************************Test Telecommand******************************** */
What's this "Test Telecommand" comment?

2024-12-13 03:02 UTC, 2BlackCats commented
Current Code works to count up when quickly pressed.

2025-01-11 21:58 UTC, NuclearTea reviewed
Nice! I think we just need to test it in person to ensure that it works and clean up some of the small things mentioned. 

Great Job!

2025-01-11 21:58 UTC, NuclearTea commented on firmware/Core/Src/gpio_handler/gpio_handler.c
> +        // char message[100];
If these comments are not needed, please remove

2025-01-11 21:58 UTC, NuclearTea commented on firmware/Makefile
I don't think this file should be edited. Also, the linker script in our repo is all caps so I don't know how this works

2025-01-11 21:58 UTC, NuclearTea commented on firmware/Core/Src/stm32l4xx_it.c
> +  HAL_GPIO_EXTI_IRQHandler(PIN_GPS_PPS_IN_Pin);
If you added this line ```HAL_GPIO_EXTI_IRQHandler(PIN_GPS_PPS_IN_Pin);``` then please put it inside the ```/* USER CODE BEGIN ... */```, otherwise, if it is auto generated, ignore this

2025-01-11 21:58 UTC, NuclearTea commented on firmware/Core/Src/stm32l4xx_it.c
> +  if (htim1.Instance != NULL)
Same comment as above

2025-01-17 01:51 UTC, 2BlackCats commented
Tested for 60 secs button press was received 60 times. Tried Repeatedly pressing button, No repeated numbers or missing numbers and signal was only received roughly every second.

2025-01-17 02:32 UTC, NuclearTea commented on firmware/Core/Src/gpio_handler/gpio_handler.c
> +    if (TIM_get_current_unix_epoch_time_ms() - GPS_last_pps_time > 800) {
Since everything is encapsulated inside this if statement, it might be worth while to make this a guard clause. Not a big deal here but good coding practice overall. https://deviq.com/design-patterns/guard-clause

2025-01-22 16:32 UTC, NuclearTea commented
@DeflateAwning Would love your input here. Everything looks good to me

2025-02-07 02:18 UTC, 2BlackCats commented
Test Plan:
Test 1: Push button every 1 sec and count every button press
Expected: System count = actual count
Result: No double counting and system count was same as actual count.

Test 2: Repeated button input of less than 0.8 s time frame.
Expected: System count < Actual count
Result: System counted inputs roughly every sec. Actual press was more than system count.

2025-02-12 01:20 UTC, NuclearTea commented
@2BlackCats Please Rebase, don't merge lol

2025-02-12 02:38 UTC, 2BlackCats commented
Rebased and retested. Still works.

2025-02-12 02:55 UTC, NuclearTea commented
@2BlackCats I think the rebase went ary. try closing this pr and creating a new one off main with your changes as commits.

2025-02-14 03:56 UTC, closed without merging