Created markdown file for configuration variables
CalgaryToSpace/CTS-SAT-1-OBC-Firmware pull request #256
Opened 2024-12-18 02:50 UTC by celinahy

- Added a markdown documenting the configuration variables and functions as declared and defined in the configuration.c file.

2024-12-22 19:01 UTC, parker-research requested changes
Looks good overall!

2024-12-22 19:01 UTC, parker-research commented on docs/Non-Critical_Notes/Configuration_Variables.md
> +**3) `CONFIG_int_config_variables[]`**:
I don't think this fits alongside the other variables in this section

2024-12-22 19:01 UTC, parker-research commented on docs/Non-Critical_Notes/Configuration_Variables.md
> +**5) `CONFIG_str_config_variables[]`**:
This isn't a configuration variable; it's an index of all the actual configuration variables. I don't think there's really a string configuration variable registered yet.

2025-01-08 03:18 UTC, celinahy commented on docs/Non-Critical_Notes/Configuration_Variables.md
> +**5) `CONFIG_str_config_variables[]`**:
Ah I see. For more clarity, I created a section called 'Configuration Variable Arrays' that contains `CONFIG_str_config_variables[]` and `CONFIG_int_config_variables[]`. To avoid confusion, I added a table of contents for the different sections of the page.

2025-01-11 21:46 UTC, NuclearTea reviewed
LGTM

2025-01-20 01:33 UTC, parker-research approved these changes
Depending on how many of these there are, we may actually want to automatically generate these docs the same way we do for telecommands. Good for now though!

2025-01-24 01:36 UTC, merged